adapters:
  r2dbc:
    host: ${ADAPTERS_R2DBC_HOST}
    port: ${ADAPTERS_R2DBC_PORT}
    database: ${ADAPTERS_R2DBC_DATABASE}
    username: ${ADAPTERS_R2DBC_USERNAME}
    password: ${ADAPTERS_R2DBC_PASSWORD}