server:
  port: 8080
spring:
  application:
    name: "Authentication"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    active: "mysql"
  data:
    redis:
      host: "localhost"
      port: 6379
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    root: "INFO"
    com.pragma.bootcamp: "TRACE"
  file:
    name: "logs/backend.log"
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
jwt:
  secret: "${JWT_SECRET}"
  expiration: 3600
security:
  login:
    max-attempts: 3
    block-duration-minutes: 15